name: Continuous Integration
on: [push, pull_request]
jobs:
  run:
    name: Execute notebook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip3 install jupyter jupytext
      - run: jupytext --to notebook --execute Loudspeaker_Explorer.md
